### PR TITLE
Rename key files to dot key

### PR DESCRIPTION
**Pull request by hannob**
It would be convenient if I could rely on all private keys being named ".key", would that be okay?

Here are some proposed name changes, not complete yet. Will do another PR if you're okay with that change.

### CODE REVIEW

**Comment by hannob** [comment]
Two motivations:
* Given that overwhelmingly the private keys are named .key, I could skip a few bytes by not storing the exension in the lookup file in badkeys. It's large enough that I'm uncomfortable having it growing too much, and having it a few megabytes smaller would be nice.
* There are a few defect keys (see https://github.com/SecurityFail/malware/commit/4cf55a3b1de7283055a120bac0a8701588339ffb ), and in a followup change I wanted to propose to rename them to something not dot key (e.g. .key.invalid). I'm currently not checking keys for validity on creation of the blocklist (due to performance reasons), and I'd prefer to have a good way of identifying defect keys.

All the keys I renamed with this PR are either unencrypted PKCS #1 or PKC #8. For practical purposes, the difference between these formats is almost irrelevant (I somewhat prefer #1 as I can see in the PEM what type of key it is), because all APIs I know of consume both these keys formats automatically. (I.e. if you do "openssl pkey -in [somekey]", it will just autodetect if it's pkcs#1 or pkcs#8, and do the same operations.)

**Comment by BenBE** [comment]
Compromise that should accommodate this use case could be:

1. Extension is always two parts: `.format.kind`, with `format` being one of `x509`, `ssh`, `pgp`, … and `kind` being in `key`, `pub`, `crt`, …
2. Invalid files get `-invalid` appended after the `.kind` part, thus making an invalid private key for a X509 certificate end in `.x509.key-invalid`
3. Metadata files keep their single `.meta` extension.
4. As PKCS#1 is about RSA private keys, PKCS#8 should be used inside the repo for storing private keys, cf. [Wikipedia on PKCS](https://en.wikipedia.org/wiki/PKCS). Except for an outer container + an OID for the key type this is essentially identical to PKCS#1, but can carry DSA and ECDSA private keys too (when defining the curve parameters you could even do Ed25519 in there).

While items 1 through 3 are quite flexible, I would strongly advice against using a mix of PKCS#1 and PKCS#8 for the private keys. Yes, DSA and ECDSA are comparatively rare when look at the numbers, but transforming one into the other is quite easy:

```python
from typing import Optional
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa

def pkcs8topkcs1(pkcs8key: str) -> Optional[str]:
    try:
        # Load the PKCS#8 private key
        private_key = serialization.load_pem_private_key(pkcs8key.encode(), password=None)

        # Check if the key is an RSA key
        if not isinstance(private_key, rsa.RSAPrivateKey):
            return None

        # Convert to PKCS#1 format
        pkcs1_key = private_key.private_bytes(encoding=serialization.Encoding.PEM, format=serialization.PrivateFormat.TraditionalOpenSSL, encryption_algorithm=serialization.NoEncryption())

        return pkcs1_key.decode()
    except Exception:
        return None
```

**Comment by hannob** [comment]
Like this ok? https://github.com/SecurityFail/kompromat/pull/103

**Comment by BenBE** [comment]
Looks fine.

**Comment by hannob** [comment]
now obsolete

**Pull request closed without merging**
