### PR TITLE
Rename Hetzner keys

### PR DESCRIPTION
**Pull request by hannob**
I noticed I wasn't done with the key renames yet...

Renaming remaining keys not named .key, as discussed here:
https://github.com/SecurityFail/kompromat/pull/102#issuecomment-2272987285

These directories also contain txt files with the SSH public key. I'm not sure we need those at all, I think they contain no interesting information that cannot be derived from the private key.

### CODE REVIEW

**Comment by BenBE** [comment]
As the ssh pubkeys are without an embedded comment I tend to agree. Go ahead there.

**Comment by hannob** [comment]
I added another commit to remove the txt files.

**Comment by hannob** [comment]
I noticed something else I'd like to change here: Some of those keys are in openssh format. (Only the newer ones, older openssh versions used PKCS format.) Given that this is much less supported, I'd prefer to have a standard PKCS-type key alongside them. (I think we already did this in other places in the repo.)
Thoughts about the naming scheme? .pkcs.key alongside every .ssh.key that is in openssh format? Or just convert them and get rid of the openssh-format version?

**Comment by BenBE** [comment]
As I'm somewhat tracking the public documents that were the leaks, I'd keep both versions; the `.pkcs.key` naming sounds reasonable for this and also aligns with what we discussed for the overall file naming.

**Comment by hannob** [comment]
done, ready to be merged.

**Pull request merged**
